repos:
- hooks:
  - id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
- hooks:
  - id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
- hooks:
  - args:
    - --safe
    - --quiet
    id: black
  repo: https://github.com/psf/black
  rev: 22.12.0
- hooks:
  - args:
    - --max-line-length=88
    - --select=E401,E711,E712,E713,E714,E721,E722,E901,F401,F402,F403,F405,F631,F632,F633,F811,F812,F821,F822,F841,F901,W191,W291,W292,W293,W602,W603,W604,W605,W606
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 5.0.4
- hooks:
  - args:
    - --autofix
    - --indent
    - '2'
    id: pretty-format-yaml
  repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
- hooks:
  - id: check-ast
  - id: check-json
  - args:
    - --autofix
    - --no-ensure-ascii
    - --no-sort-keys
    id: pretty-format-json
  - exclude: template\.yaml$|\.aws-sam/
    id: check-yaml
  - id: check-merge-conflict
  - args:
    - --maxkb=200
    id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.9.1
