---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |-
  python3.10

  SAM Template for common infrastructure
Parameters:
  GitHubOrg:
    Description: Name of GitHub organization/user (case sensitive)
    Type: String
  RepositoryName:
    Description: Name of GitHub repository (case sensitive)
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String
  OIDCAudience:
    Description: Audience supplied to configure-aws-credentials.
    Default: "sts.amazonaws.com"
    Type: String

  DevOpenAIKey:
    Type: String
    Description: OpenAI API Key for Development
  DevPromptLayerKey:
    Type: String
    Description: PromptLayer API Key for Development
  DevHuggingFaceKey:
    Type: String
    Description: HuggingFace API Key for Development
  DevPineconeKey:
    Type: String
    Description: Pinecone API Key for Development
  DevWeviateKey:
    Type: String
    Description: Weviate API Key for Development
  DevMilvusKey:
    Type: String
    Description: Milvus API Key for Development
  DevGoogleKey:
    Type: String
    Description: Google API Key for Development
  DevMetaKey:
    Type: String
    Description: Meta API Key for Development
  DevAnthropicKey:
    Type: String
    Description: Anthropic API Key for Development

  ProdOpenAIKey:
    Type: String
    Description: OpenAI API Key for Production
  ProdPromptLayerKey:
    Type: String
    Description: PromptLayer API Key for Production
  ProdHuggingFaceKey:
    Type: String
    Description: HuggingFace API Key for Production
  ProdPineconeKey:
    Type: String
    Description: Pinecone API Key for Production
  ProdWeviateKey:
    Type: String
    Description: Weviate API Key for Production
  ProdMilvusKey:
    Type: String
    Description: Milvus API Key for Production
  ProdGoogleKey:
    Type: String
    Description: Google API Key for Production
  ProdMetaKey:
    Type: String
    Description: Meta API Key for Production
  ProdAnthropicKey:
    Type: String
    Description: Anthropic API Key for Production


Conditions:
  CreateOIDCProvider: !Equals
    - !Ref OIDCProviderArn
    - ""

Resources:

  DevDeployerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for GitHubActions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:DescribeUserPool
              - cognito-idp:DescribeUserPoolClient
              - cognito-idp:GetUser
            Resource:
              - arn:aws:cognito-idp:us-east-1:330659553592:userpool/us-east-1_NcdVCUDOV
#              - arn:aws:cognito-idp:us-east-1:439638760367:userpool/1_5j6i3QGRW
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref DevAiSecrets
              - !Ref ProdAiSecrets
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource:
              - !GetAtt DevSessionTable.Arn
              - !GetAtt DevAgentConfigTable.Arn
              - !GetAtt DevLeadTable.Arn
              - !GetAtt ProdSessionTable.Arn
              - !GetAtt ProdAgentConfigTable.Arn
              - !GetAtt ProdLeadTable.Arn
          - Effect: Allow
            Action:
              - cloudformation:DescribeStacks
            Resource:
              - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*'
          - Effect: Allow
            Action:
              - events:PutEvents
            Resource:
              - !GetAtt DevEventBus.Arn
              - !GetAtt ProdEventBus.Arn
#          - Effect: Allow
#            Action:
#              - iam:GetRole
#              - iam:AttachRolePolicy
#            Resource:
#                  - !Sub



  GitHubRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !Ref GithubOidc
                - !Ref OIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

  ProdSessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
        - AttributeName: session_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DevSessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
        - AttributeName: session_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


  ProdAgentConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: client_id
        AttributeType: S
      - AttributeName: profile_name
        AttributeType: S
      KeySchema:
      - AttributeName: client_id
        KeyType: HASH
      - AttributeName: profile_name
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


  DevAgentConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
        - AttributeName: profile_name
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
        - AttributeName: profile_name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DevLeadTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
        - AttributeName: lead_id
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
        - AttributeName: lead_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ProdLeadTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
        - AttributeName: lead_id
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
        - AttributeName: lead_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  AiEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: AiEventBus


  ProdAiSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secrets for Production Service
      SecretString: !Sub |
        {
          "openai_api_key": "${ProdOpenAIKey}",
          "promptlayer_api_key": "${ProdPromptLayerKey}",
          "huggingface_api_key": "${ProdHuggingFaceKey}",
          "pinecone_api_key": "${ProdPineconeKey}",
          "weviate_api_key": "${ProdWeviateKey}",
          "milvus_api_key": "${ProdMilvusKey}",
          "google_api_key": "${ProdGoogleKey}",
          "meta_api_key": "${ProdMetaKey}",
          "anthropic_api_key": "${ProdAnthropicKey}"
        }

  DevAiSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secrets for Development Service
      SecretString: !Sub |
        {
          "openai_api_key": "${DevOpenAIKey}",
          "promptlayer_api_key": "${DevPromptLayerKey}",
          "huggingface_api_key": "${DevHuggingFaceKey}",
          "pinecone_api_key": "${DevPineconeKey}",
          "weviate_api_key": "${DevWeviateKey}",
          "milvus_api_key": "${DevMilvusKey}",
          "google_api_key": "${DevGoogleKey}",
          "meta_api_key": "${DevMetaKey}",
          "anthropic_api_key": "${DevAnthropicKey}"
        }

  DevInfraTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DevInfraTopic
      DisplayName: Dev Infrastructure Notifications

  DevBusinessTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DevBusinessTopic
      DisplayName: Dev Business Notifications


  ProdInfraTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ProdInfraTopic
      DisplayName: Production Infrastructure Notifications

  ProdBusinessTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ProdBusinessTopic
      DisplayName: Production Business Notifications

  DevEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: DevEventBus

  ProdEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: ProdEventBus

#  DevGptAgentLeadToolSuccessRule:
#    Type: AWS::Events::Rule
#    Properties:
#      EventBusName: !Ref DevEventBus
#      EventPattern:
#        source:
#          - "dev-ai-api"
#        detail-type:
#          - "GptAgent Lead Connection Tool Event"
#      State: ENABLED
#      Targets:
#        - Arn: !GetAtt DevSendLeadToLeadMomentum.Arn
#          Id: SendLeadToLeadMomentum
#
#  DevSendLeadToLeadMomentum:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: index.handler
#      Runtime: python3.10
#      CodeUri: ./src
#      Events:
#        MyEvent:
#          Type: CloudWatchEvent
#          Properties:
#            Pattern:
#              source:
#                - "dev-ai-api"

Outputs:
  WordsOfWarning:
    Description: WARNING
    Value: "These outputs are used by other stacks. These outputs are open to extension, but closed to modification."


  DevDomainName:
    Description: This is a static value, someone should make it dynamic.
    Value: www.samvange.net

#  ProdDomainName:
#    Description: This is a static value, someone should make it dynamic.
#    Value: www.samvange.net


  # Secrets
  DevAiSecrets:
    Description: ARN of the Development Secrets
    Value: !Ref DevAiSecrets
  ProdAiSecrets:
    Description: ARN of the Production Secrets
    Value: !Ref ProdAiSecrets

  # Policies
#  DevCommonAccessPolicy:
#    Description: Dynamic name of the policy that allows reading of these outputs and access to this stack's resources.
#    Value:
#      Ref: DevCommonAccessPolicy
#
#  ProdCommonAccessPolicy:
#    Description: Dynamic name of the policy that allows reading of these outputs and access to this stack's resources.
#    Value:
#      Ref: ProdCommonAccessPolicy

  # Tables
  DevSessionTable:  # SESSION
    Description: Dynamic name of the DEVELOPMENT DynamoDB table for SESSIONS
    Value:
      Ref: DevSessionTable
  DevAgentConfigTable:  # PREFERENCES/AGENTCONFIGS
    Description: Dynamic name of the DEVELOPMENT DynamoDB table for AGENTCONFIGS
    Value:
      Ref: DevAgentConfigTable
  DevLeadTable:
    Description: Dynamic name of the DEVELOPMENT DynamoDB table for LEADS  # LEADS
    Value:
      Ref: DevLeadTable

  Role:
    Value: !GetAtt GitHubRole.Arn

  ProdSessionTable:  # SESSION
    Description: Dynamic name of the PRODUCTION DynamoDB table for SESSIONS
    Value:
      Ref: ProdSessionTable
  ProdAgentConfigTable:  # PREFERENCES/AGENTCONFIGS
    Description: Dynamic name of the PRODUCTION DynamoDB table for AGENTCONFIGS
    Value:
      Ref: ProdAgentConfigTable
  ProdLeadTable:
    Description: Dynamic name of the PRODUCTION DynamoDB table for LEADS  # LEADS
    Value:
      Ref: ProdLeadTable

  STAGES:
    Description: STAGES
    Value: dev,prod
  EventBus:
    Description: EventBus
    Value: !Ref AiEventBus
  DevInfrastructureTopic:
    Description: InfrastructureTopic
    Value: !Ref DevInfraTopic
  DevBusinessTopic:
    Description: BusinessTopic
    Value: !Ref DevBusinessTopic
  InfrastructureTopic:
    Description: InfrastructureTopic
    Value: !Ref ProdInfraTopic
  BusinessTopic:
    Description: BusinessTopic
    Value: !Ref ProdBusinessTopic
