#!/usr/bin/env sh
set -e

export PREFIX='poetry run python -m '
export REGEX='^(?![.]|venv).*'

#${PREFIX}pytest -n 3 --dist=loadfile --cov-report term-missing --cov-report=xml:coverage.xml --cov=commitizen tests/
${PREFIX}pytest tests/
${PREFIX}black openbrain tests --check
${PREFIX}ruff openbrain/ tests/
#${PREFIX}mypy openbrain/ tests/  # TODO: fix mypy errors, this is great insight!
${PREFIX}commitizen -nr 3 check --rev-range origin/main..
