name: Release to development environment
on:
  workflow_dispatch: #disabled
#  push:
#    tags:
#      - v[0-9]+.[0-9]+.[0-9]+-dev.*

permissions:
    id-token: write
    contents: write
jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    name: "Deploy (NOT YET IMPLEMENTED)"
    if: needs.release.outputs.tag != ''

    steps:

      - name: Deploy
        run: |
          echo "NOT YET IMPLEMENTED"
          echo "This needs to deploy the new code to production environments that are using it."
          exit 0
