deploy:
  needs: [release]
  name: "Build release"
  if: needs.release.outputs.tag != ''

  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

    - name: Switch to correct tag