name: Test dev branch and deploy to pypi-test
on:
  push:
    tags:
      - build
#      - ci

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
env:
  AWS_GITHUB_ROLE_ARN: ${{ secrets.AWS_GITHUB_DEV_DEPLOYER_ROLE_ARN }}
  AWS_REGION: us-east-1
  PROJECT: openbrain
  REPOSITORYNAME: openbrain
  GITHUBORG: svange
  DISABLE_TUNER_API_MODE: 1
  INFRA_STACK_NAME: ai-infra
  SECRET_STORE_FRIENDLY_NAME: DevAiSecrets
  COMMON_ACCESS_POLICY_FRIENDLY_NAME: DevCommonAccessPolicy
  SESSION_TABLE_FRIENDLY_NAME: DevSessionTable
  AGENT_CONFIG_TABLE_FRIENDLY_NAME: DevAgentConfigTable
  LEAD_TABLE_FRIENDLY_NAME: DevLeadTable
  INFRASTRUCTURE_TOPIC_FRIENDLY_NAME: InfrastructureTopic
  BUSINESS_TOPIC_FRIENDLY_NAME: BusinessTopic
  EVENTBUS_FRIENDLY_NAME: DevEventBus
  OPENAI_API_KEY: ${{ secrets.DEV_OPENAI_KEY }}
jobs:
  # fail if not on dev
  branch-check:
    runs-on: ubuntu-latest
    if: github.ref_name != 'dev'
    steps:
      - name: Fail if not on dev
        run: |
          echo "${{ github.ref_name }} only allowed on dev branch"
          exit 1

  submit-pr:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["build"]'), github.ref_name)
    needs: branch-check
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: GH Actions auto-release 🐍 ${{github.ref_name}}
          committer: GitHub Actions <samuelvange@gmail.com>
          branch: release/${{github.ref_name}}
          base: main

