name: Test and submit PR to main
on:
  push:
    branches:
      - dev
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
    with:
      tag: ${{ github.ref_name }}
      AWS_GITHUB_ROLE_ARN: "${{ secrets.AWS_GITHUB_DEV_DEPLOYER_ROLE_ARN }}"
      AWS_REGION: us-east-1
      GITHUBORG: svange
      OPENAI_API_KEY: "${{ secrets.DEV_OPENAI_KEY }}"


  #  create-pr:
#    runs-on: ubuntu-latest
#    if: !StartsWith(github.ref_name, 'test')
#    needs: run-tests
#    steps:
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v5
#        with:
#          title: GH Actions auto-release 🐍 ${{github.ref_name}}
#          committer: GitHub Actions <samuelvange@gmail.com>
#          branch: release/${{github.ref_name}}
#          base: main
#
#
#


  # if not on dev or master, and tag is "feat", "fix", "perf", "build", "ci"
  # merge and push to dev
#  update-git-dev:
#    runs-on: ubuntu-latest
#    needs: publish-test
#    if: startsWith(github.context.commit.message, 'fix:') or startsWith(github.context.commit.message, 'feat:') or startsWith(github.context.commit.message, 'perf:') or startsWith(github.context.commit.message, 'build:') or startsWith(github.context.commit.message, 'ci:')
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.head_ref }}
#          fetch-depth: 0
#      - name: Git operations to merge and push to dev
#        run: |
#          git config --local user.email "github-actions[bot]@users.noreply.github.com"
#          git config --local user.name "github-actions[bot]"
#          git fetch
#          git rebase origin/dev
#          git checkout dev
#          git pull origin dev
#          git merge --no-ff ${{ github.head_ref }}
#          git commit -a -m "github-actions[bot] - ${{ github.ref_name }} - ${{ github.sha }}"
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          branch: dev
