#name: Test main branch and deploy to prod stage
#on:
#  push:
#    branches:
#    - main
#permissions:
#  id-token: write # This is required for requesting the JWT
#  contents: read  # This is required for actions/checkout
#env:
#  SECRET_STORE_FRIENDLY_NAME: DevWoxomAiSecrets
#  COMMON_ACCESS_POLICY_FRIENDLY_NAME: DevCommonAccessPolicy
#  SESSION_TABLE_FRIENDLY_NAME: DevSessionTable
#  AGENT_CONFIG_TABLE_FRIENDLY_NAME: DevAgentConfigTable
#  LEAD_TABLE_FRIENDLY_NAME: DevLeadTable
#  INFRASTRUCTURE_TOPIC_FRIENDLY_NAME: InfrastructureTopic
#  BUSINESS_TOPIC_FRIENDLY_NAME: BusinessTopic
#  EVENTBUS_FRIENDLY_NAME: EventBus
#  STAGES_FRIENDLY_NAME: STAGES
#  INFRA_STACK_NAME: woxom-ai-infra
#  STAGE: ${{ inputs.STAGE }}
#  DEV_API_URL: https://dev.woxomai.com
#  PROD_API_URL: https://www.woxomai.com
#  DEV_WOXOM_API_KEY: ${{ secrets.DEV_WOXOM_API_KEY }}
#  PROD_WOXOM_API_KEY: ${{ secrets.PROD_WOXOM_API_KEY }}
#  AWS_REGION: us-east-1
#  APP_NAME: woxom-ai-api
#  PROJECT: prod-woxom-ai-api
#jobs:
#  pipenv-script:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#
#    steps:
#      - name: Configure AWS credentials from Test account
#        uses: aws-actions/configure-aws-credentials@v3
#        with:
#          audience: sts.amazonaws.com
#          role-to-assume: arn:aws:iam::439638760367:role/GithubWoxomSolutionsOrg
#          role-session-name: ${{env.PROJECT}}-deployer
#          aws-region: ${{ env.AWS_REGION }}
#
#      - name: Check out repository code
#        uses: actions/checkout@v2
#
#      # Setup Python (faster than using Python container)
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.10"
#
#      - name: Install pipenv
#        run: |
#          python -m pip install --upgrade pipenv wheel
#      - id: cache-pipenv
#        uses: actions/cache@v1
#        with:
#          path: ~/.local/share/virtualenvs
#          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
#
#      - name: Install dependencies
#        if: steps.cache-pipenv.outputs.cache-hit != 'true'
#        run: |
#          pipenv install --deploy --dev
#
#      - name: Run tests
#        id: test-output
#        run: |
#          pipenv run test
#
#      - name: Deploy to prod
#        id: deploy-output
#        run: |
#          pipenv run deploy_skip_tests --stage prod
#
#      - name: Run remote tests
#        id: remote-test-output
#        run: |
#          pipenv run test_remote
#
##      # Checkout master branch
##      - name: Checkout master branch
##        uses: actions/checkout@v2
##        with:
##          ref: origin/master
##          token: ${{ secrets.GITHUB_TOKEN }}
##
##      # pull changes from dev branch
##      - name: Pull changes from dev branch
##        run: |
##          git pull origin dev
##
##      # commit changes to master branch
##      - name: Commit changes to master branch
##        run: |
##          git commit -m "AUTO-COMMIT: Merge dev branch into master branch"
##
##      # submit pull request to master branch
##      - name: Create Pull Request to main
##        uses: peter-evans/create-pull-request@v5
##        with:
##          token: ${{ secrets.GITHUB_TOKEN }}
##          title: 'AUTO: All deployment tests passed after a push to dev, merge dev into master?'
##          body: |
##            AUTO-GENERATED PULL REQUEST:
##            This pull request was automatically generated by a GitHub Actions workflow running on the dev branch.
##
##            TEST RESULTS:
##            ${{ steps.test-output.outputs.test-output }}
##
##            DEPLOY RESULTS:
##            ${{ steps.deploy-output.outputs.deploy-output }}
##          labels: deploy, automated pr
##
#
