name: Upload Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          # pin poetry to 1.3.2 due to https://github.com/python-poetry/poetry/issues/7611
          python -m pip install -U pip poetry==1.3.2 #mkdocs mkdocs-material
          poetry --version
          poetry install

      - name: Main Configure PyPI token
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
        if: ! contains(github.ref, 'dev')

      - name: Main Publish to PyPI
        if: ! contains(github.ref, 'dev')
        env:

          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./scripts/publish

      - name: Dev Configure PyPI token
        run: poetry config pypi-token.pypi "${{ secrets.TEST_PYPI_API_KEY }}"
        if: contains(github.ref, 'dev')

      - name: Dev Publish to TestPyPI
        if: contains(github.ref, 'dev')
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./scripts/publish -r testpypi
